-- liquibase formatted sql
-- changeset kirill:2

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    profile_picture VARCHAR(255),
    status VARCHAR(255),
    description VARCHAR(255),
    google_id VARCHAR(255),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_name VARCHAR(255),
    conversation_picture VARCHAR(255),
    conversation_type VARCHAR(255),
    last_message VARCHAR(255),
    last_message_at TIMESTAMP,
    created_at TIMESTAMP,
    CONSTRAINT conversation_type_check CHECK (conversation_type IN ('PRIVATE', 'GROUP'))
);

CREATE TABLE chat_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_admin BOOLEAN NOT NULL,
    joined_at TIMESTAMP WITHOUT TIME ZONE,
    conversation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,


    CONSTRAINT uk_user_conversation UNIQUE (user_id, conversation_id),

    CONSTRAINT fk_participant_user FOREIGN KEY (user_id)
        REFERENCES users (id),

    CONSTRAINT fk_participant_conversation FOREIGN KEY (conversation_id)
        REFERENCES conversation (id)
);



CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    status VARCHAR(255),
    sent_at TIMESTAMP,
    sender_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    CONSTRAINT fk_msg_sender FOREIGN KEY (sender_id) REFERENCES users (id),
    CONSTRAINT fk_msg_conversation FOREIGN KEY (conversation_id) REFERENCES conversation (id),
    CONSTRAINT messages_status_check CHECK (status IN ('SENT', 'DELIVERED', 'READ'))
);


CREATE INDEX idx_msg_conversation ON messages (conversation_id);
CREATE INDEX idx_msg_sent_at ON messages (sent_at);

CREATE TABLE room (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    creator_id BIGINT,
    file_id VARCHAR(255),
    file_name VARCHAR(255),
    local_path VARCHAR(255),
    playback_time DOUBLE PRECISION,
    is_playing BOOLEAN NOT NULL,
    status VARCHAR(255),
    created_at TIMESTAMP,
    CONSTRAINT fk_room_creator FOREIGN KEY (creator_id) REFERENCES users (id),
    CONSTRAINT room_status_check CHECK (status IN ('PROCESSING', 'READY', 'ERROR'))
);


